trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildVersionNumber: '1.0.$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Assembly-Info-NetFramework@2
  inputs:
    VersionNumber: $(buildVersionNumber)
    FileVersionNumber: $(buildVersionNumber)
    InformationalVersion: $(buildVersionNumber)

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: 'pack'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'buildVersion'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    externalEndpoint: 'de0b499f-2eb5-4fb4-b76f-d2c12acb6053'