trigger:
- master

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildVersion: '1.0.$(Build.BuildId)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: Assembly-Info-NetCore@2
  inputs:
    InsertAttributes: true
    PackageId: 'CodeStream.LogDNA'
    Authors: 'Allen Firth'
    Company: 'CodeStream Systems'
    Product: 'CodeStream LogDNA Classes'
    Description: 'Helpful classes for RedBear.LOGDNA / LogDNA'
    Copyright: 'Copyright © $(date:YYYY) $(date:DD.MM.YYYY DD MMMM YYYY HH:mm a) CodeStream Systems Pty Ltd'
    PackageProjectUrl: 'https://github.com/codestreamsystems/codestream.logdna'
    PackageIconUrl: 'https://www.codestream.co.za/img/CodeStream-05.png'
    RepositoryUrl: 'https://github.com/codestreamsystems/codestream.logdna'
    VersionNumber: '$(buildVersion)'
    FileVersionNumber: '$(buildVersion)'
    InformationalVersion: '$(buildVersion)'
    PackageVersion: '$(buildVersion)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: MSBuild@1
  inputs:
    solution: '**/*.csproj'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/t:pack /p:packageversion=$(buildVersion)'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    nuGetFeedType: 'external'
    externalEndpoint: 'de0b499f-2eb5-4fb4-b76f-d2c12acb6053'